### PR TITLE
Adding a gruvbox variation theme

### PR DESCRIPTION
**Pull request by FarParticul**
After I switched to gruvbox, I found a theme from s-n-g in pyradio, but I didn't like it a bit, so I redesigned it, if you want you can approve it, then not.

### CODE REVIEW

**Comment by s-n-g** [comment]
Sure, I like it!

Can you please make the following changes?

```
Status Bar          #2e2a27 #a89984
```


```
transparency        2
```



and rename the file to `gruvbox-dark-by-farparticul.pyradio-theme`?

Then I will merge it, along with a couple of code changes I have completed

**Comment by FarParticul** [comment]
> Sure, I like it!
> 
> Can you please make the following changes?

no problem, I'll put it in right away.

**Comment by s-n-g** [comment]
Please be advised I have renamed 
```
gruvbox-dark-by-farparticul.pyradio-theme
```
to
``` 
gruvbox_dark_by_farparticul.pyradio-theme
```

**Comment by FarParticul** [comment]
> Please be advised I have renamed
> 
> ```
> gruvbox-dark-by-farparticul.pyradio-theme
> ```
> 
> to
> 
> ```
> gruvbox_dark_by_farparticul.pyradio-theme
> ```

okey

**Pull request merged**
