### PR TITLE
Fixed typos in readme files and filenames

### PR DESCRIPTION
**Pull request by jazzsewera**
Nothing changed in terms of content. Only some minor typo and styling fixes.

### CODE REVIEW

**Comment by jazzsewera** [comment]
Sorry, I didn't know that 'licence' is correct in BrE. You can probably exclude my change by modifying my commit.

**Comment by s-n-g** [comment]
Can you please modify your commit for me? (I don't seem to find the way to do it)

While you are at it, please
1. Restore the  LICENCE file
2. Omit html styling changes; they come from a pre-commit hook running [pandoc](https://pandoc.org), so they will be overwritten anyway

Thanks
S.

**Comment by jazzsewera** [comment]
I did everything you asked for, all in the same commit in order not to make a mess in your history.

I also spotted some other minor typos. Please review them and if everything is okay, merge my branch with the master :)

Cheers,

B.

**Comment by s-n-g** [comment]
Thank you very much.
Really, really appreciated

**Comment by jazzsewera** [comment]
If I have time in the near future, I will try to address some issues.
But for now, my pleasure :)

**Pull request merged**
