### PR TITLE
several typo fixes in README.md

### PR DESCRIPTION
**Pull request by Wikinaut**

### CODE REVIEW

**Comment by s-n-g** [comment]
Thank you so much!

**Comment by Wikinaut** [comment]
Personally,  I would prefer to change `titles logging` to `title logging` globally. 

What do you think?

And, how and when is the README.html changed, how does this work?

**Comment by s-n-g** [comment]
Yes, I like the change you propose, I will update globally.

README.html is updated offline through a script/pandoc. This goes for all HTML files, so they will all be updated when a new release is out :)

**Comment by s-n-g** [comment]
Changed in **v. 0.9.1**

**Pull request merged**
